# Generated by Django 4.0.3 on 2022-04-19 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expenses', '0022_expense_type_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subsription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('type', models.CharField(choices=[('S', 'Subsription'), ('I', 'Installment')], max_length=12, verbose_name='subcription/installment')),
                ('frequency', models.CharField(choices=[('1', 'Monthly'), ('3', 'Quarterly'), ('12', 'Yearly')], max_length=12, verbose_name='Due')),
                ('next_due', models.DateField()),
                ('autopay', models.BooleanField(default=True)),
                ('amount', models.PositiveIntegerField()),
                ('currency', models.CharField(choices=[('EGP', 'EGP'), ('USD', 'USD'), ('EUR', 'EUR'), ('AED', 'AED')], max_length=3, verbose_name='Currency')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.category_type')),
            ],
        ),
    ]
