# Generated by Django 3.2.5 on 2022-03-05 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Payment Method', 'verbose_name_plural': 'Payment Methods'},
        ),
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('DB', 'Debit Account'), ('CC', 'Credit Card'), ('WK', 'Work Card')], max_length=25, verbose_name='Account type'),
        ),
    ]
