# Generated by Django 3.2.5 on 2022-03-05 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_alter_expense_store'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='value',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='value_currency',
            new_name='amount_currency',
        ),
    ]
