# Generated by Django 2.2.10 on 2022-03-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_auto_20220311_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='amount_currency',
        ),
        migrations.AddField(
            model_name='expense',
            name='currency',
            field=models.CharField(choices=[('AED', 'AED'), ('EGP', 'EGP'), ('EUR', 'EUR'), ('USD', 'USD')], default=1, max_length=25, verbose_name='Currency'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
    ]
