# Generated by Django 2.2.10 on 2022-03-12 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0009_auto_20220312_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='currency',
        ),
    ]
