# Generated by Django 2.2.10 on 2022-03-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0010_remove_expense_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='currency',
            field=models.CharField(choices=[('EGP', 'EGP'), ('USD', 'USD'), ('EUR', 'EUR'), ('AED', 'AED')], default=1, max_length=3, verbose_name='Currency'),
            preserve_default=False,
        ),
    ]
