# Generated by Django 4.0.3 on 2022-03-18 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0016_category_type_remove_category_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_type',
        ),
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='expenses.category_type'),
            preserve_default=False,
        ),
    ]
