# Generated by Django 4.0.3 on 2022-03-19 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0017_remove_category_category_type_category_category_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='category_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expenses.category_type'),
        ),
    ]
