# Generated by Django 4.0.3 on 2022-03-19 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0018_expense_category_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='card',
            new_name='deleted',
        ),
        migrations.AddField(
            model_name='category_type',
            name='icon',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
