# Generated by Django 4.0.3 on 2022-03-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0019_rename_card_expense_deleted_category_type_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='store',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
