# Generated by Django 4.0.3 on 2022-03-22 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0020_alter_expense_store'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='store',
            new_name='note',
        ),
    ]
