# Generated by Django 4.0.3 on 2022-04-23 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0025_remove_subscription_name_subscription_category_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='category_type',
        ),
    ]
