# Generated by Django 4.0.3 on 2022-04-23 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0027_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='frequency',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], max_length=12, verbose_name='Due'),
        ),
    ]
